<a href="https://colab.research.google.com/github/angui100/Deeplearning4j_Keras_Model/blob/master/TensorFlow_Data_Observation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Set up TensorFflow 2.0 working environment

In [0]:
try:
  %tensorflow_version 2.x
except Exception:
  pass

import tensorflow as tf

In [0]:
print(tf.__version__)

2.1.0


In [0]:
import numpy as np

### Play with tensorflow data<br/>
A TensorFlow variable is the best way to represent shared, persistent state manipulated by your program.

Variables are manipulated via the tf.Variable class. A tf.Variable represents a tensor whose value can be changed by running ops on it. Specific ops allow you to read and modify the values of this tensor. Higher level libraries like tf.keras use tf.Variable to store model parameters. 

In [0]:
#Defining a constant 
tensor_20 = tf.constant([[23, 4], [32, 51]])
tensor_20.shape

TensorShape([2, 2])

In [0]:
tensor_20

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [0]:
tensor_20.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [0]:
tensor_20.dtype

tf.int32

**Assign numpy array to tensor variable**

In [0]:
#Convert numpy array to tensor
numpy_tensor = np.array([[23, 4], [32, 51]])
tensor_from_numpy = tf.constant( numpy_tensor )
tensor_from_numpy

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [32, 51]])>

In [0]:
#Convert Tensorflow tensor to numpy array
numpy_from_tensor = np.array( tensor_from_numpy )
numpy_from_tensor

array([[23,  4],
       [32, 51]])

### Tensor variable operations

In [0]:
tf_variable_1 = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf_variable_1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [0]:
#change variable value for particular element in a tensor variable
tf_variable_1[0, 2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [0]:
#@title

my_variable = tf.Variable(tf.zeros([1, 2, 3]))

In [0]:
#@title
my_variable

In [0]:
#Addition between a scalar and a tensor
tensor = tf.constant([[1, 2], [3, 4]])
tensor + 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

In [0]:
#Multiplication between a scalar and a tensor
tensor * 5

In [0]:
#Applying Numpy functions on TensorFlow tensor
tensor_changed = np.square(tensor)
#print(tensor_changed)

In [0]:
tensor_changed

In [0]:
np.sqrt( tensor )

### Dot product between two tensors

In [0]:
tensor_20

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [0]:
np.dot(tensor, tensor_20)

array([[ 87, 106],
       [197, 216]], dtype=int32)

### String functions 

In [0]:
tf_string = tf.constant("TensorFlow")

In [0]:
tf_string

<tf.Tensor: shape=(), dtype=string, numpy=b'TensorFlow'>

In [0]:
tf.strings.length(tf_string)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [0]:
tf.strings.unicode_decode( tf_string, "UTF8")

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119], dtype=int32)>

### Storing arrays of strings

In [0]:
tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [0]:
#iterating the string array
for string in tf_string_array:
  print( string )

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)
